services:
  kodi-rpi:
    image: p-boon/kodi-rpi
    hostname: kodi-rpi
    stop_grace_period: 20s
    devices:
      - /dev/dri
      - /dev/input:/dev/input
      - /dev/snd:/dev/snd
      - /dev/cec0
      - /dev/video10
      - /dev/video19
      - /dev/media0
      - /dev/dma_heap
    group_add:
      - video
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/root/.kodi/
